# Generated by Django 5.2.4 on 2025-07-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('link', models.URLField()),
                ('bias', models.CharField(blank=True, max_length=50, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('embedded', models.BooleanField(default=False)),
            ],
        ),
    ]
